 [build]
  command = "CI= npm run build"
  publish = "dist"
  
[[headers]]
  for = "/main.js"
  [headers.values]
    Content-Type = "text/javascript"



[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

    [build.environment]
  NODE_VERSION = "18"
